
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'levity_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'levity-bigquery'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# dbt_project.yml
vars:
  segment:
    segment_page_views_table: "{{ref('pages_view')}}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
#models:
  #geography:
      # Applies to all files under models/example/
      #geography:
          #+materialized: table

  intercom:
    intercom__company_history_pass_through_columns: [custom_company_industry_list, custom_company_organization_type, custom_company_size_list]
    intercom__contact_history_pass_through_columns: [location_country, custom_utm_campaign, custom_status, custom_utm_term, custom_utm_source, custom_utm_medium, custom_utm_content, custom_referral_url, custom_lead_score, custom_company_size, custom_company_industry, custom_organization_type, custom_type_of_data, custom_use_case_ai_block, custom_use_case_pattern, custom_use_case, custom_ai_type, custom_employee_role, custom_tool_experience, custom_source, custom_sentiment, custom_account_approved]             
  
  intercom_source:
    intercom__company_history_pass_through_columns: [custom_company_industry_list, custom_company_organization_type, custom_company_size_list]
    intercom__contact_history_pass_through_columns: [location_country, custom_utm_campaign, custom_status, custom_utm_term, custom_utm_source, custom_utm_medium, custom_utm_content, custom_referral_url, custom_lead_score, custom_company_size, custom_company_industry, custom_organization_type, custom_type_of_data, custom_use_case_ai_block, custom_use_case_pattern, custom_use_case, custom_ai_type, custom_employee_role, custom_tool_experience, custom_source, custom_sentiment, custom_account_approved]