version: 2

models:
    - name: created_flow
      description: users who created at least 1 Flow together with date of the fist Flow created
      columns:
        - name: user_id
        - name: date_flow_created
    - name: created_trigger
      description: users who created at least 1 Trigger in at least 1 Flow together with date of the first Trigger created
      columns:
        - name: user_id
        - name: date_first_trigger_created
    - name: connected_ai_block
      description: users who connectd at least 1 AI Block to at least 1 Flow together with date of the first AI Block connected
      columns:
        - name: user_id
        - name: date_first_aiblock_connected
    - name: created_action  
      description: users who created at least 1 Action in at least 1 Flow together with date of the first Action created
      columns:  
        - name: user_id
        - name: date_first_40datapoints_uploaded
 