version: 2
models:
  - name: data_upload_events
    description: "This table is instrumental to the sending of Segment \"Datapoints\
      \ Added\" events. Since a user may add at the same time hundreds of data points,\
      \ it makes no sense to translate each of them in an event. Therefore, every\
      \ hour we count how many data points were added and we send to Segment just\
      \ one event with the detail of the count. The aggregation is conditional on\
      \ some factors: the ID of the user, the ID of the AI Block and some additional\
      \ more specific factors. At the end, each record of this table will be sent\
      \ to Segment as a \"Datapoints Added\" event. \n\n"
    meta:
      consumer: customer success
    columns:
      - name: user_id
        description: 'Unique ID of the user: user_frontegg_id'
      - name: workspace_id
        description: 'Unique ID of the workspace: frontegg_tenant_id'
      - name: net_data_points
        description: Count of the data points that were uploaded
      - name: is_userflow_data
        description: "- \"yes\" if the data points come from one of the datasets that\
          \ we have the users download during the onboading tour\n\n- \"no\" otherwise"
      - name: is_template
        description: "- \"yes\" if the AI Block is an AI Block Template clone - whenever\
          \ a Template is cloned a `Datapoints Added` event with `is_template = \"\
          yes\"` occurs because part of the template training data are copied into\
          \ the clone\n\n- \"no\" otherwise"
      - name: is_human_in_the_loop
        description: '- "yes" if the data points were not actively uploaded by the
          user,  by rather automatically by our backend because flagged as to be reviewed
          through HITL. As a reminder, when HITL is active, the data points associated
          with very uncertain predictions are classified manually by the user via
          Slack and are automatically added to the training data in the unlabelled
          bucket


          - "no" otherwise'
      - name: aiblock_id
        description: 'Unique ID of the AI Block: ID of the datasets_dataset table'
      - name: time_stamp
        description: Time at which the last data uploaded operation occurred (within
          the 60' window)
  - name: prediction_events
    description: 'This table is instrumental to the sending of Segment "Predictions
      Done" events. Since a workspace may make at the same time hundreds of predictions,
      it makes no sense to translate each of them in an event. Therefore, every hour
      we count how many prdictions were made and we send to Segment just one event
      with the detail of the count. The aggregation is conditional on some factors:
      the ID of the user, the ID of the AI Block and some additional more specific
      factors. At the end, each record of this table will be sent to Segment as a
      "Predictions Done" event.'
    columns:
      - name: user_id
        description: 'Unique ID of the user: frontegg_user_id'
      - name: workspace_id
        description: 'Unique ID of the wokspace: frontegg_tenant_id'
      - name: aiblock_id
        description: 'Unique ID of the AI Block: ID of the datasets_dataset backend
          table'
