version: 2

models:
    - name: funnel_flow_table
      columns:
        - name: user_id
        - name: user_email_address
        - name: date_user_onboarded
        - name: date_first_flow_created
        - name: date_first_trigger_created
        - name: date_first_aiblock_connected
        - name: date_first_action_created
        - name: activation_flag
    
         