version: 2

sources:
  - name: intercom
    tables:
      - name: contact_history
        description: '{{ doc("contact_history") }}'
  - name: google_cloud_postgresql_public
    tables:
      - name: auth_user
      - name: accounts_userprofile
      - name: datasets_dataset
      - name: datasets_data
      - name: prediction_models_trainingrun
      - name: prediction_models_prediction
      - name: prediction_models_classifier
      - name: prediction_models_classifierversion


      