version: 2

sources:
  - name: intercom
    tables:
      - name: contact_history
      - name: contact_tag_history
      - name: tag
  - name: public
    tables:
      - name: production_auth_user
      - name: production_accounts_userprofile
      - name: production_datasets_dataset
      - name: production_datasets_datalabel
      - name: production_datasets_data
      - name: production_prediction_models_trainingrun
      - name: production_prediction_models_prediction
      - name: production_prediction_models_classifier
      - name: production_prediction_models_classifierversion
      - name: production_workflows_workflow
      - name: production_workflows_block
      - name: production_workflows_classifierblock


      