version: 2

sources:
  - name: dbt_giancarlo_intercom
    tables:
      - name: intercom__contact_enhanced
      - name: intercom__company_enhanced
  - name: intercom 
    tables:
      - name: contact_history
  - name: google_sheets
    tables: 
      - name: typeform_first_step
  - name: google_analytics
    tables:
      - name: users
  - name: labs
    tables: 
      - name: vetevo
  - name: django_backend_api
    tables:
      - name: dataset_deleted
      - name: block_deleted
      - name: workflow_deleted
      - name: label_deleted
      - name: classifier_deleted
      - name: classifier_version_deleted
      - name: classifier_block_deleted
      - name: data_deleted
  - name: google_cloud_function_frontegg_complete
    tables:
      - name: user_table
      - name: tenant_table
      - name: user_tenant_table
      - name: tenant_metadata_table
  - name: public
    tables:
      - name: production_auth_user
      - name: production_accounts_userprofile
      - name: production_datasets_dataset
      - name: production_datasets_datalabel
      - name: production_datasets_data
      - name: production_prediction_models_trainingrun
      - name: production_prediction_models_prediction
      - name: production_prediction_models_classifier
      - name: production_prediction_models_classifierversion
      - name: production_workflows_workflow
      - name: production_workflows_block
      - name: production_workflows_classifierblock


      