version: 2

models:
    - name: onboarded_user
      description: real users of the platform together with onboarding date
      columns:
        - name: user_id
        - name: user_email_address
        - name: date_user_onboarded
    - name: created_ai_block
      description: users who created at least 1 AI Block together with date of the first AI Block created
      columns:
        - name: user_id
        - name: date_first_aiblock_created
    - name: uploaded_data
      description: users who uploaded data to at least 1 AI Block together with date of the first data upload
      columns:
        - name: user_id
        - name: date_first_datapoint_uploaded
    - name: uploaded_40datapoints  
      description: users who uploaded at least 40 data points to at least 1 AI Block together with date when the first >40 data uploaded ended
      columns:  
        - name: user_id
        - name: date_first_40datapoints_uploaded
    - name: training_run  
      description: users who trained at least 1 AI Block together with date when the first AI Block was trained
      columns:
        - name: user_id
        - name: date_first_training_run
    - name: prediction_made  
      description: users who made at least 1 prediction through at least 1 AI Block together with date when the first prediction was made
      columns:
        - name: user_id
        - name: date_first_prediction_made
    - name: made_50predictions  
      description: users who made at least 50 predictions through at least 1 AI Block together with date when the first 50 prediction were made
      columns:
        - name: user_id
        - name: date_first_prediction_made
    
