version: 2
models:
  - name: subscriptions
    meta:
      consumer: customer success
    description: 'This table shows, for each onboarded workspace, the plan ID of the
      chosen plan and whether the workspace is enjoying the free trial or it has become
      a paying customer.'
    columns:
      - name: user_id
        description: 'Unique ID of the workspace: frontegg_user_id of the user that
          got onboarded'
      - name: email
        description: 'Unique ID of the workspace: email address of the user that got
          onboarded'
