version: 2
models:
  - name: subscriptions
    meta:
      consumer: customer success
    description: 'This table shows, for each onboarded workspace, the plan ID of the
      chosen plan and whether the workspace is enjoying the free trial or it has become
      a paying customer.'
