version: 2
models:
  - name: subscriptions
    meta:
      consumer: customer success
    description: 'This table shows, for each onboarded workspace, the plan ID of the
      chosen plan and whether the workspace is enjoying the free trial or it has become
      a paying customer.'
    columns:
      - name: user_id
        description: 'Unique ID of the workspace: `frontegg_user_id` of the user that
          got onboarded'
      - name: email
        description: 'Unique ID of the workspace: email address of the user that got
          onboarded


          **Foreign Key** to enrich the profile of the onboarded user in **HubSpot**'
      - name: workspace_id
        description: 'Unique ID of the workspace: `frontegg_tenant_id`'
      - name: is_onboarded
        description: 'Whether the workspace is onboarded: always take value `yes`
          for workspaces that are part of this table.


          For general info: this variable in HubSpot is named `Is Onboarded` and takes
          value `added` for all those users that get invited to the workspace.'
      - name: lifecyclestage
        description: "Takes the following values:\n\n- `salesqualifiedlead` (HubSpot:\
          \ `Sales Qualified Lead`) - if the workspace is enjoying th free trial\n\
          \n- `customer` (HubSpot: `Customer`) - if the workspace is a paying customer\n\
          \nFor general info: this variable in HubSpot is named `Lifecycle stage`"
      - name: hs_lead_status
        description: "Takes the following values:\n\n- `Active in free plan` (HubSpot:\
          \ `Active in Free Plan`) - if the workspace is enjoying th free trial\n\n\
          - `Paid plan` (HubSpot: `Paid Plan`) - if the workspace is a paying customer\n\
          \nFor general info: this variable in HubSpot is named `Lead status`"
      - name: subscription_plan_id
        description: "Unique ID of the payment plan\n\nRefer to HubSpot property `Subscription\
          \ Plan ID` for additional details"
